# Generated by Django 2.2.7 on 2019-11-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20191128_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='lifetime_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='links',
            name='short_url',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
