# Generated by Django 2.2.7 on 2019-11-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20191128_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='short_url',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
