# Generated by Django 2.2.7 on 2019-11-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20191129_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
