# Generated by Django 2.2.7 on 2019-11-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20191130_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
