# Generated by Django 2.2.7 on 2019-11-30 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_auto_20191130_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='created_at',
        ),
        migrations.AddField(
            model_name='links',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
